### ISSUE TITLE
Remove the api_key parameter

### ISSUE THREAD

**Issue by Jhonnyr97** [patterns-ai-core/qdrant-ruby#9]
api_key must not be required in localhost

```ruby
require 'qdrant'

client = Qdrant::Client.new(
  url: "your-qdrant-url"
)```

**Comment by andreibondarev** [comment]
@Jhonnyr97 I think we can just add a comment to the README with:
```ruby
client = Qdrant::Client.new(
  url: "your-qdrant-url",
  api_key: "your-qdrant-api-key" # Optional for localhost
)
```
Thoughts?

**Comment by andreibondarev** [comment]
The `api_key:` is actually not required: https://github.com/patterns-ai-core/qdrant-ruby/blob/main/lib/qdrant/client.rb#L16
